# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181023_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='desc',
            field=models.TextField(verbose_name='类型描述'),
        ),
    ]
