# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181023_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(verbose_name='购买数量')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'CartInfo',
                'verbose_name': '购物车',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='goods',
            field=models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='users',
            field=models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.CASCADE, to='index.Users', verbose_name='用户'),
        ),
    ]
